name: Build & Publish
on:
  push:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Build and Publish
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - name: Run wasm-pack
        run: wasm-pack build --target web --release

      - name: List files in /pkg
        run: |
          ls ${{ github.workspace }}/pkg

      - name: Copy index.html to alexfoxgil.github.io
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          destination_repo: alexfoxgill/alexfoxgill.github.io
          source_file: ${{ github.workspace }}/index.html
          destination_folder: demo
          user_email: email@alexfoxgill.com
          user_name: alexfoxgill
        
      - name: Copy pkg to alexfoxgill.github.io
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          destination_repo: alexfoxgill/alexfoxgill.github.io
          source_file: ${{ github.workspace }}/pkg/
          destination_folder: demo
          user_email: email@alexfoxgill.com
          user_name: alexfoxgill